// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCONTRASTADJ_H
#define XCONTRASTADJ_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcontrastadj_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XContrastadj_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XContrastadj;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XContrastadj_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XContrastadj_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XContrastadj_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XContrastadj_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XContrastadj_Initialize(XContrastadj *InstancePtr, u16 DeviceId);
XContrastadj_Config* XContrastadj_LookupConfig(u16 DeviceId);
int XContrastadj_CfgInitialize(XContrastadj *InstancePtr, XContrastadj_Config *ConfigPtr);
#else
int XContrastadj_Initialize(XContrastadj *InstancePtr, const char* InstanceName);
int XContrastadj_Release(XContrastadj *InstancePtr);
#endif

void XContrastadj_Start(XContrastadj *InstancePtr);
u32 XContrastadj_IsDone(XContrastadj *InstancePtr);
u32 XContrastadj_IsIdle(XContrastadj *InstancePtr);
u32 XContrastadj_IsReady(XContrastadj *InstancePtr);
void XContrastadj_EnableAutoRestart(XContrastadj *InstancePtr);
void XContrastadj_DisableAutoRestart(XContrastadj *InstancePtr);

void XContrastadj_Set_adj(XContrastadj *InstancePtr, u32 Data);
u32 XContrastadj_Get_adj(XContrastadj *InstancePtr);

void XContrastadj_InterruptGlobalEnable(XContrastadj *InstancePtr);
void XContrastadj_InterruptGlobalDisable(XContrastadj *InstancePtr);
void XContrastadj_InterruptEnable(XContrastadj *InstancePtr, u32 Mask);
void XContrastadj_InterruptDisable(XContrastadj *InstancePtr, u32 Mask);
void XContrastadj_InterruptClear(XContrastadj *InstancePtr, u32 Mask);
u32 XContrastadj_InterruptGetEnabled(XContrastadj *InstancePtr);
u32 XContrastadj_InterruptGetStatus(XContrastadj *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
