// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcontrastadj.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XContrastadj_CfgInitialize(XContrastadj *InstancePtr, XContrastadj_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XContrastadj_Start(XContrastadj *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL) & 0x80;
    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XContrastadj_IsDone(XContrastadj *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XContrastadj_IsIdle(XContrastadj *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XContrastadj_IsReady(XContrastadj *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XContrastadj_EnableAutoRestart(XContrastadj *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XContrastadj_DisableAutoRestart(XContrastadj *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_AP_CTRL, 0);
}

void XContrastadj_Set_adj(XContrastadj *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_ADJ_DATA, Data);
}

u32 XContrastadj_Get_adj(XContrastadj *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_ADJ_DATA);
    return Data;
}

void XContrastadj_InterruptGlobalEnable(XContrastadj *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_GIE, 1);
}

void XContrastadj_InterruptGlobalDisable(XContrastadj *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_GIE, 0);
}

void XContrastadj_InterruptEnable(XContrastadj *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_IER);
    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_IER, Register | Mask);
}

void XContrastadj_InterruptDisable(XContrastadj *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_IER);
    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_IER, Register & (~Mask));
}

void XContrastadj_InterruptClear(XContrastadj *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrastadj_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_ISR, Mask);
}

u32 XContrastadj_InterruptGetEnabled(XContrastadj *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_IER);
}

u32 XContrastadj_InterruptGetStatus(XContrastadj *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XContrastadj_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRASTADJ_AXILITES_ADDR_ISR);
}

