# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/system_system_ila_2_0.xci
# IP: The module: 'system_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/bd_1519.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519 || ORIG_REF_NAME==bd_1519} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_1/bd_1519_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_g_inst_0 || ORIG_REF_NAME==bd_1519_g_inst_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_2/bd_1519_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_aw_0 || ORIG_REF_NAME==bd_1519_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_3/bd_1519_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_w_0 || ORIG_REF_NAME==bd_1519_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_4/bd_1519_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_b_0 || ORIG_REF_NAME==bd_1519_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_5/bd_1519_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_ar_0 || ORIG_REF_NAME==bd_1519_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_6/bd_1519_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_r_0 || ORIG_REF_NAME==bd_1519_slot_1_r_0} -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0_ooc.xdc

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/bd_1519_ooc.xdc

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/system_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/system_system_ila_2_0.xci
# IP: The module: 'system_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/bd_1519.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519 || ORIG_REF_NAME==bd_1519} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_1/bd_1519_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_g_inst_0 || ORIG_REF_NAME==bd_1519_g_inst_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_2/bd_1519_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_aw_0 || ORIG_REF_NAME==bd_1519_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_3/bd_1519_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_w_0 || ORIG_REF_NAME==bd_1519_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_4/bd_1519_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_b_0 || ORIG_REF_NAME==bd_1519_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_5/bd_1519_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_ar_0 || ORIG_REF_NAME==bd_1519_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_6/bd_1519_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1519_slot_1_r_0 || ORIG_REF_NAME==bd_1519_slot_1_r_0} -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1519_ila_lib_0 || ORIG_REF_NAME==bd_1519_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/ip/ip_0/bd_1519_ila_lib_0_ooc.xdc

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/bd_0/bd_1519_ooc.xdc

# XDC: c:/Users/wnagds/Desktop/hdmi_ov5640_2017/hdmi_ov5640_2017.srcs/sources_1/bd/system/ip/system_system_ila_2_0/system_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
